### ISSUE TITLE
Fehlende Übersetzung / VERSION Scanner

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#16]
Es fehlen die Übersetzungen für das RESULT: `INTERNAL_ERROR_OCCURED`

Bitte schnellstmöglich einpflegen.

Der Fall tritt auf, wenn beim VERSION-Scanner ein Fehler aufritt und kein Ergebnis geliefert werden kann.

**Comment by Lednerb** [comment]
@Skeeve @PetraStruck 

Bitte gegenchecken und bei Bedarf anpassen, sonst Issue schließen.

**Comment by Skeeve** [comment]
Alles Super!
