### ISSUE TITLE
Fehlende Übersetzung / VERSION.CMS_MIGHT_UPTODATE 

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#20]
Der oben genannte String fehlt, bitte asap integrieren.

**Comment by SniperSister** [comment]
"Die verwendete CMS-Version ist möglicherweise veraltet. Nur eine der in Frage kommenden Versionen (%version) ist aktuell. Bitte prüfen Sie manuell die verwendete Version"

**Comment by Skeeve** [comment]
#21
