### ISSUE TITLE
TLS.EARLYCCS_VULNERABLE_POSITIVE

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#30]
Der oben genannte String fehlt momentan anscheinend.

Bitte prüfen.

**Comment by Skeeve** [comment]
@ic0ns - Bitte prüfen, was noch fehlt.

Welche Texte brauchen wir noch für die "neuen" Scanner?

**Comment by Skeeve** [comment]
Nachtrag.
Ein kurzer Vergleich zwischen dem Develop-README und den vorhanden Texten hat ergeben, dass diese hier noch fehlen. @ic0ns: Bitte nachreichen:

* CERTIFICATE_WEAK_SIGN_ALGORITHM
* CIPHERSUITE_CBC
* CVE20162107_VULNERABLE
* EARLYCCS_VULNERABLE

**Comment by ic0ns** [comment]
Hey,
@PetraStruck hatte EarlyCCS schon eingepflegt. https://github.com/SIWECOS/translations/commit/e2c1336b37114221aa4e19286c77d4ea54e3ef07
Oder fehlt hier was anderes?

Bezüglich der anderen Identifier: Die Texte fehlen weil wir die Tests nach Absprache entfernt hatten. Diese scheinen nur noch in der Readme zu fehlen. Ich werde sie entfernen.

**Comment by Skeeve** [comment]
@PetraStruck Du darfst die Verzeichnisse nicht irgendwie benennen. Die Namen müssen schon dem entstprechen, was im Scanner verwendet wird. Also nicht "Early-CCS" sondern "EARLYCCS_VULNERABLE".

**Comment by PetraStruck** [comment]
oh ja, das war mein Fehler. Ich benenne das Verzeichnis um.
