### ISSUE TITLE
Texte für MAIL_TLS - Scanner integrieren

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#32]
Die Texte für folgende Scanner müssen integriert werden:

- `IMAP_TLS`
- `IMAPS_TLS`
- `POP3_TLS`
- `POP3S_TLS`
- `SMTP_TLS`
- `SMTPS_TLS`
- `SMTP_MSA_TLS`

~Sowie für einen weiteren `SMTP`- Scanner, dessen Namen noch nicht feststeht:~

- ~https://github.com/SIWECOS/WS-TLS-Scanner/issues/19~

**Comment by Skeeve** [comment]
@ic0ns: Wir brauchen Input… ;)

**Comment by Lednerb** [comment]
Da es sich ebenfalls um den TLS-Scanner handelt, gehe ich davon aus, dass lediglich die Texte von "Server / HTTPS" auf das jeweilige Protokoll etc. angepasst werden muss.

Der Großteil sollte ähnlich / gleich sein.

**Comment by Skeeve** [comment]
> Assumptions are dangerous things to make, and like all dangerous things to make -- bombs, for instance, or strawberry shortcake -- if you make even the tiniest mistake you can find yourself in terrible trouble.

― Lemony Snicket, The Austere Academy 

https://www.goodreads.com/quotes/tag/assumptions

**Comment by ic0ns** [comment]
Hey, Sascha liegt genau richtig. Ich muss nochmal durch alle Texte gehen und die HTTP spezifischen teile austauschen. Für den Anfang können wir einfach die TLS texte übernehmen.

**Comment by Lednerb** [comment]
@PetraStruck @Skeeve 

der 7. Scanner heißt `SMTP_MSA_TLS`, ich habe das Issue dementsprechend angepasst.

**Comment by Lednerb** [comment]
Done by #33

**Comment by Lednerb** [comment]
@Skeeve @PetraStruck 

Die Scanner-Namen wurden nicht beachtetet.
Alle Scanner haben das `_TLS` - Suffix.

Travis baut die Übersetzungen momentan ohne dieses Suffix zusammen.
Bitte anpassen.

**Comment by PetraStruck** [comment]
Ist in Arbeit, siehe https://github.com/SIWECOS/translations/pull/37
