### ISSUE TITLE
[Allgemein] _DESCRIPTION nur im Fehlerfall?

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#4]
Wir haben Scanner bzw. Übersetzungen, bei denen es einen `_DESCRIPTION` Eintrag gibt.

Beispiel:

https://github.com/SIWECOS/translations/blob/21a6fb629e5b32e747b727a0f090b9664b8f5b16/build/siwecos-business-layer/de/HEADER.php#L71

Die `_DESCRIPTION` sollen vom Text her jedenfalls nur ausgegeben werden, wenn nicht der score von 100 erreicht wurde.

-----------------------

Meiner Meinung nach, sollte das eher aufgeteilt werden:

1. Description beim Klick auf *Mehr Informationen* immer Anzeigen, sonst sieht man ja keine weiteren Informationen, die Sinn ergeben, außer: Alles OK!

2. Beschreibung und Fehlermeldung trennen.
Beispiel im oberen Fall:
Letzter Satz zu `X_CONTENT_TYPE_OPTIONS_NEGATIVE` umziehen und in `sind hier nicht korrekt gesetzt.` abwandeln

3. Im Report werde ich dann die korrekte Fehlermeldung (siehe #3) mit ausgeben, sodass ein Aufzählungspunkt mit folgender Meldung erscheint:
https://github.com/SIWECOS/translations/blob/21a6fb629e5b32e747b727a0f090b9664b8f5b16/build/siwecos-business-layer/de/HEADER.php#L105

**Comment by Lednerb** [comment]
![Bildschirmfoto vom 2019-03-29 19-42-23](https://user-images.githubusercontent.com/2056876/55255399-de341400-525a-11e9-822f-86363625b667.png)

**Comment by Skeeve** [comment]
Sehe ich anders.

Die Beschreibung ist bisher in allen 49 Tests dafür ausgelegt, das Problem zu beschreiben. Wenn das geändert werden soll, dann sollten bitte die Scanner Ersteller die gelieferten 49 Beschreibungen so anpassen, daß sie Allgemeingültig sind.

Ich halte das für unnötige Arbeit.

In der Anwendungsoberfläche sollte bei einem Postiven Test einfach nur stehen "Alles gut". Gegebenenfalls liefert ein Scanner mehr Informationen über das , was gefunden Wurde, das wird dann bei "Mehr Informationen" angezeigt. Das Beispiel "Ws wurden keine Sources gefunden" halte ich für eine schlechtes Beispiel. Dieser Text kann ersatzlos wegfallen. Ein Text wie »Der Header "text/html; charset=utf-8" ist korrekt gesetzt und entspricht den Empfehlungen. « hingegen ist hilfreich, weil man hier auch sieht, was der Server geliefert hat.

Fazit:
- Keine Änderung an den Descriptions. Sie beschreiben den Negativfall genauer
- Änderung an der Weboberfläche - Verbergen von "Mehr Informationen", wenn es nicht mehr Informationen gibt
- Änderungen am Scanner - Keine testdetails liefern, wenn sie keinen Mehrwert haben

Vorschlag: Dieses Ticket schließen.
 
Ich habe ein paar mehr Leute assigned um deren Meinung zu erfragen.

**Comment by Lednerb** [comment]
@Skeeve ok, mit deinem, Fazit gehe ich auch mit. Dann als Bezeichnung ~`error_description`~ `result_description` und es passt für mich.

Muss nur klar sein, dass damit dann keine allgemeine Test-Beschreibung gemeint ist.

**Comment by Skeeve** [comment]
Im Moment heißt das Verzeichnis in translations "Description". Wäre kein Aufwand das in "Result_Description" umzubenennen und auch in den Scripten anzupassen. Aber ist es das wert? Immerhin werden die Bezeichner dadurch NOCH länger.

Noch mal als Referenz: wir haben
- Background - Beschreibt den Hintergrund des Tests, die Motivation
- Consequence - Beschreibt die Folgen einer Fehl-/Nicht-Konfiguration
- Description - Beschreibt was auf dem Server falsch ist
- Solution_Tips - Beschreibt was getan werden kann

Theoretisch ließe sich alles auch in der Weboberfläche einbauen.
