### ISSUE TITLE
siwecos Exception-Nachrichten / Domain Verifizierung

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#8]
Es gibt folgende neue Text-Strings für https://github.com/SIWECOS/siwecos-business-layer/issues/121 und https://github.com/SIWECOS/siwecos-business-layer/issues/120:

- `siwecos.CONNECTEXCEPTION`
- `siwecos.TOOMANYREDIRECTSEXCEPTION`
- `siwecos.BADRESPONSEEXCEPTION`
- `siwecos.CLIENTEXCEPTION` (sollte im Betrieb nicht auftauchen, da HTTP `4xx` deaktiviert sind
- `siwecos.SERVEREXCEPTION`
- `siwecos.EXCEPTION` (sollte nicht auftauchen, "Unbekannter Fehler")

Für weitere Informationen siehe:

1. [Guzzle Dokumentation](http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions)
2. [PHPUnit Test in der BLA](https://github.com/SIWECOS/siwecos-business-layer/blob/b45117a184ce2e2e67110f123772c20cfe34c54c/tests/Unit/DomainVerifierTest.php#L155-L192)

**Comment by Skeeve** [comment]
Edit by @Lednerb:
Vorschläge aktualisiert.

Gibt es Textvorschläge dazu, @Lednerb?

* siwecos.CONNECTEXCEPTION
  Es konnte keine Verbindung zu ihrem Server aufgebaut werden.
* siwecos.TOOMANYREDIRECTSEXCEPTION
  Ihr Server sendet zuviele "Redirects".
* siwecos.BADRESPONSEEXCEPTION
  Ihr Server liefert eine unerwartete Antwort.
* siwecos.CLIENTEXCEPTION (sollte im Betrieb nicht auftauchen, da HTTP 4xx deaktiviert sind
  Beim Verbindungsaufbau zu Ihrem Server ist ein unbekannter Fehler aufgetreten.
* siwecos.SERVEREXCEPTION
  Ihr Server liefert eine unerwartete Antwort.
* siwecos.EXCEPTION (sollte nicht auftauchen, "Unbekannter Fehler")
  Beim Verbindungsaufbau zu Ihrem Server ist ein unbekannter Fehler aufgetreten.

Alle möglichst mit Wiki-Erklärtexten.

**Comment by Lednerb** [comment]
Die Texte könnten auch noch einen Platzhalter aufnehmen, sowas wie:

siwecos.EXCEPTION:
Beim Verbindungsaufbau zu Ihrem Server ist ein unbekannter Fehler aufgetreten.
Die Fehlermeldung lautet: 
:MESSAGE

**Comment by Lednerb** [comment]
Zu klären wäre noch, wo die Übersetzungen implementiert werden sollten (@SniperSister)

Einerseits ist die BLA lediglich für die Übersetzung der Reports zuständig (momentan) und das Frontend muss "Es ist ein Fehler aufgetreten" ebenfalls enthalten und dem Nutzer etwas mitzuteilen ist im Allgemeinen eher Frontend-Sache.

Andererseits ist das translations-Repo direkt die BLA integriert, sollten Textänderungen vorgenommen werden, so kann das direkt vom Übersetzungsteam hier gemacht werden und es erfordert kein Re-deploy von Webapp und Plugins.

Daher der Vorschlag, das in die BLA zu integrieren.

**Comment by Lednerb** [comment]
Ein optionaler Platzhalter `:EXCEPTION` wurde hinzugefügt.

Wird dieser im Text verwendet, so wird die komplette Exception-Meldung ausgegeben.

**Comment by Skeeve** [comment]
Ist es richtig, dass diese Fehler bei der Valisierung gemeldet werden?

Vorschläge:

CONNECTEXCEPTION

> Es konnte keine Verbindung zu Ihrem Server aufgebaut werden.
> 
> Der Fehlertext lautet: :EXCEPTION


TOOMANYREDIRECTSEXCEPTION

> Ihr Server scheint nicht korrekt konfiguriert zu sein, da er zuoft weiterleitet.
> 
> Der Fehlertext lautet: :EXCEPTION

BADRESPONSEEXCEPTION

> Ihr Server scheint nicht korrekt konfiguriert zu sein, da er eine ungültige Antwort liefert.
> 
> Der Fehlertext lautet: :EXCEPTION

CLIENTEXCEPTION (sollte im Betrieb nicht auftauchen, da HTTP 4xx deaktiviert sind

> Bei der Validierung Ihrer Seite ist ein unbekannter Fehler aufgetreten.
> 
> Der Fehlertext lautet: :EXCEPTION

SERVEREXCEPTION

> Bei der Validierung Ihrer Seite ist ein Fehler aufgetreten.
> 
> Der Fehlertext lautet: :EXCEPTION

EXCEPTION

> Bei der Validierung Ihrer Seite ist ein unbekannter Fehler aufgetreten.
> 
> Der Fehlertext lautet: :EXCEPTION

**Comment by Lednerb** [comment]
Korrekt.
