### ISSUE TITLE
Build ist nicht korrekt

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/translations#9]
Bei allen ausgegebenen Übersetzungsdateien (`.php`) fehlt bspw. der `SCANNER_NAME`.

Bitte analysieren und prüfen, ob alle vorhandenen Texte und `translationStringId`s auch entsprechend gemapped werden.

**Comment by Skeeve** [comment]
SCANNER_NAME ist behoben https://github.com/SIWECOS/translations/blob/v2/dir2lang

Fehlte noch mehr? Beispiele?
